### PR TITLE
checkoutShippingAddressUpdate mutation

### PR DESCRIPTION
**Pull request by darol100**
This PR adds support to the `checkoutShippingAddressUpdate` mutation.

https://help.shopify.com/api/custom-storefronts/storefront-api/reference/mutation/checkoutshippingaddressupdate

### CODE REVIEW

**Comment by minasmart** [comment]
Hey there, could you do a rebase and doc-regen?

**Comment by darol100** [comment]
Hey @minasmart, I have updated the docs and fixed all conflicts.

**Comment by darol100** [comment]
Hey @minasmart, Any update testing this PR?

**Comment by minasmart** [comment]
Same as before. Please remove the changes to the `/docs` folder, because causes merge conflicts on every following PR. Once the few outstanding ones are in, I'll generate the docs in a separate PR.

**Comment by darol100** [comment]
@minasmart , I misread your previous message. I thought you asked me to update the `docs/` folder. I will remove the changes in the docs.

**Comment by pgrimaud** [comment]
Any update about merging this branch? It could be very useful 😄

**Comment by rebeccajfriedman** [comment]
@pgrimaud If you are still waiting on this functionality, please feel free to make a new PR for it (without including changes to docs) and we will merge that.

**Comment by alistairholt** [comment]
What happened here? This is a missing feature IMO.

**Pull request closed without merging**
