### PR TITLE
Implemented generation of API (yuidoc) docs

### PR DESCRIPTION
**Pull request by yomexzo**
In preparation for serving docs (http://shopify.github.io/js-buy-sdk/) from `/docs` directory, this PR allows you to generate API docs for references (branches or tags).

Running `npm run build-doc` would generate/update API docs based on **yuidoc comments** in the `/src` directory for the `master` branch and put it in `/docs/api/master`.

The script accepts options which you can view by running `npm run build-doc --help`.

The only option at the moment is the `references` option which allows you to define for which references you want to generate API docs.

For example, `npm run build-doc --references master,v0.2.2` would generate API docs into `/docs/api/master` and `/docs/api/v0.2.2`.

This way, users would be able to browse docs from different versions.

👀 @Shopify/javascript 

EDIT:
there are 41 file changes because I brought in our `yuidoc` theme from `gh-pages` branch.
But there are actually three files - `/scripts/build-doc`, `/scripts/util/doc-builder.js` & `/scripts/util/yuidoc.js`

### CODE REVIEW

**Comment by yomexzo** [comment]
Sample run

```
➜  js-buy-sdk git:(feature/docs) node scripts/build-doc --references master,v0.2.2
Building ....

info: Getting all references within the repo
info: Picking objects for each requested references
info: Found 2 references ( master, v0.2.2 )

info: Getting tree for master
info: Checking out master

info: Getting tree for v0.2.2
info: Checking out v0.2.2

info: Generating API docs
info: Generating docs for master info yuidoc
info: Generating docs for v0.2.2 info yuidoc
info: Completed in 0.829 seconds info yuidoc

info: Deleting SRC directories
info: Removing master/src
info: Removing v0.2.2/src

Done building
```

**Comment by arapehl** [comment]
Is YUIDoc being maintained given that [maintenance of YUI stopped in mid 2014](https://yahooeng.tumblr.com/post/96098168666/important-announcement-regarding-yui)?

**Comment by minasmart** [comment]
@arapehl it's [actively maintained on github](https://github.com/yui/yuidoc/commits/master)?

**Comment by minasmart** [comment]
I think that post is regarding the yui library. Not the doc system.

**Comment by minasmart** [comment]
@yomexzo what's the status of this PR? Has it been updated to reflect your docs roadmap, and hosting docs out of `/docs`?

**Comment by yomexzo** [comment]
@minasmart, this PR is in line with the docs roadmap but it has a whole bunch of commits that are unnecessary and shouldn't go in to `master`. This is because the work started before the roadmap was created. I'd be closing this PR in favour of a new, clean one.

**Pull request closed without merging**
