### PR TITLE
add fetch for browser to deps

### PR DESCRIPTION
**Pull request by tessalt**
@minasmart @mikkoh

### CODE REVIEW

**Comment by minasmart** [comment]
Approved!

**Comment by tessalt** [comment]
still not convinced this solves anything

**Comment by tessalt** [comment]
well it solves _some_ things

**Comment by mikkoh** [comment]
Totally agree with this. Actually I was thinking really all the polyfills should go into deps not dev deps.

I believe these are the only two missing from deps:
- Base64
- core-js

**Comment by minasmart** [comment]
Does this fix all the things @tessalt ?

**Comment by tessalt** [comment]
@minasmart remains to be seen. I think combined with the build all the things update

**Comment by minasmart** [comment]
Then let's :shipit:

**Pull request merged**
