### PR TITLE
add deploying docs

### PR DESCRIPTION
**Pull request by tessalt**
I'm not sure what the best order to do things in is. The way I've written it, you will have to push the version bump commit to master, which isn't great. However, if you run `npm version` from the branch, then the npm package and master will not be at the same sha, since master will have a merge commit. Thoughts? 

@minasmart @richgilbank @harismahmood89

### CODE REVIEW

**Comment by richgilbank** [comment]
I think this makes sense for now. One thing though is that we should decide if it's worth having a [CHANGELOG.md](https://github.com/Shopify/js-buy-sdk/blob/master/CHANGELOG.md) since the release notes should summarize things anyway. Thoughts? My inclination would be to :fire: it down.

**Comment by tessalt** [comment]
agreed, notes for releases should be the source of truth.

**Comment by minasmart** [comment]
Disagree. Release notes are a fairly hard to discover feature of GitHub that lives entirely outside the got repo and have no aggregation mechanism. While I agree that we've done a poor job of maintaining the change log, it actually lives in the repo and provides aggregated, discoverable, data. I have a script that should get built into our release processes, but I feel like punting everything to release notes makes it easier to hide us not documenting releases. The change log makes our obligation more apparent.

**Comment by tessalt** [comment]
Fair enough. I think ideally having both if we had a script to keep them in sync would be ideal, since i do really like the "download zip" feature of gh releases.

**Comment by minasmart** [comment]
The script I have uses the github API to pull in release notes, then appends them to the doc. It's in ruby, but I could rewrite it, or we could just roll with it. Whatever you think is best.

**Comment by tessalt** [comment]
ruby doesn't bother me.

**Comment by minasmart** [comment]
For reference: https://gist.github.com/minasmart/7a531198e9559ed11a330e23caa642bd

**Comment by minasmart** [comment]
It doesn't bother me, it's just a second language dependency for the repo. However, if it's only shopifolk who are able to delpoy, it shouldn't be that big a deal.

**Comment by minasmart** [comment]
Also, to be clear, I don't think we shouldn't use releases. I just think we should use both, and mirror appropriately. 👍

**Comment by yoadsn** [comment]
@tessalt A thought, If you would to rebase your branch on top of master and only then run `npm version` on it, your (immediate) merge onto master would be a fast-forward which should maintain the sha. (Assuming not commits to master between rebase and merge, which is a reasonable assumption for version closing step).

Did I miss something?

**Comment by minasmart** [comment]
@yoadsn I feel at that point we're blessing a PR as the next version, when it really represents a point in time on master. Functionally it's the same, but workflow-wise I think it's much easier to run these changes from master.

**Comment by yoadsn** [comment]
@minasmart Totally agree, it's a workflow derived decision. I worked on projects where dev branch sets the next version, and others where it was master. Just wanted to point out the sha problem is solvable with FF.

**Pull request merged**
