### PR TITLE
[FEATURE] Discover Node and NPM version dependencies

### PR DESCRIPTION
**Pull request by minasmart**
While testing supported versions of npm and node, it became apparent that it wasn't that difficult to add support for uncovered versions.

As of this PR, we support node v0.10+, npm 2 and npm 3.

Also adds Parallel CircleCI builds in 5 node variants.

### CODE REVIEW

**Comment by minasmart** [comment]
Resolves #62

**Comment by minasmart** [comment]
CC: @richgilbank 

Take a look @lreeves and @tessalt

**Comment by lreeves** [comment]
Looks good, I'd probably mention in the build script to set Circle to use 5 VMs or whatever.

**Comment by tessalt** [comment]
👍

**Pull request merged**
