### PR TITLE
bump graphql js client version

### PR DESCRIPTION
**Pull request by lyninx**
Need support from the latest version of `graphql-js-client` to continue work on `buy-button-js`

### CODE REVIEW

**Comment by lyninx** [comment]
```AssertionError: src/client.js should pass lint.
1:8 - No default export found in module. import/default``` ???

**Comment by lyninx** [comment]
when i test using `npm test` everything passes, but with yarn i get linting failures.
probably due to this:
`warning "eslint-plugin-shopify@14.0.0" has incorrect peer dependency "eslint@3.3.x".`

**Comment by minasmart** [comment]
Have you tried changing [this line](https://github.com/Shopify/js-buy-sdk/blob/44afd640fe0543b3a245e507a15e64d1463a9874/scripts/rollup-tests.js#L24) to `module: true`, and removing `jsnext: true`?

**Comment by lyninx** [comment]
tried it... but no luck! node resolve doesn't seem to continue to look for jsnext:main even after setting `jsnext: false`. i'll go ahead and ship the graphql-js-client patch to fix it until we figure it out.

**Pull request merged**
