### PR TITLE
Adding the readme for the examples section

### PR DESCRIPTION
**Pull request by richgilbank**
Adds a readme to the cart example directory since it wasn't documented anywhere previously: https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/cart-example-not-working-334493

I think this is the right place to put this, but open to suggestions @tessalt @harismahmood89

### CODE REVIEW

**Comment by richgilbank** [comment]
Bump 😄

**Comment by tessalt** [comment]
does `ENV=examples` still need to be set?

**Comment by richgilbank** [comment]
Not that I know of, but I've never seen it needed previously, so you know more about it than I!

**Comment by harismahmood89** [comment]
Do we want to add more details about what the requirements are? The person in the ticket example is quite confused

**Comment by richgilbank** [comment]
Any requirements in particular you have in mind?

**Comment by tessalt** [comment]
@richgilbank if you just pull down the repo and follow this instruction does it work?

**Comment by richgilbank** [comment]
It does, but I figured we should add a note as to what to open the browser to, so I've done that. GH isn't picking up new commits at the moment though, will try pushing the change tomorrow.

**Comment by minasmart** [comment]
npm run examples sets the end variable. This looks good :smile: :+1:

**Comment by harismahmood89** [comment]
@richgilbank maybe just listing off node and browser requirements?

**Comment by minasmart** [comment]
LGTM.

**Comment by richgilbank** [comment]
Good call @harismahmood89 - added.

**Pull request merged**
