### PR TITLE
Moved api docs into a subdirectory named current

### PR DESCRIPTION
**Pull request by yomexzo**
This PR moves all api docs into a directory named `current` within `docs/api`.

With this, our API docs will be browsed via `/api/current` on shopify.github.io/js-buy-sdk. And would allow other versions to be served. Say `/api/v0.2.0`.

However, every directory in `docs/api` except `current` is ignored so you'd have to pull the repo and manually generate the docs for other version using script added in #205.

It is part of the docs roadmap listed in #202

👀 @tessalt @mikkoh @minasmart @tanema

### CODE REVIEW

**Comment by tessalt** [comment]
🆗

**Comment by mikkoh** [comment]
LGTM. This is not a significant change but its a good one if we want to generate other versions of docs.

**Comment by mikkoh** [comment]
After talking with @minasmart about documents and versioning I think we shouldn't version previous versions of docs. This would mean we don't need a current version. It's still important that at any time a developer would be able to generate and view docs from previous versions.

**Comment by yomexzo** [comment]
Agreed @mikkoh. I should have closed this way back. Closing now.

**Pull request closed without merging**
