### PR TITLE
Simplified Brocfile.js and added in a .babelrc file

### PR DESCRIPTION
**Pull request by mikkoh**
Hey I'm putting up this PR for discussions sake.

I've simplified the `Brocfile.js` where it doesn't register/setup Babel preset's and plugins. Doing this also allows for `babel-register` to be removed as a dev dep.

Thoughts? @minasmart @richgilbank @yomexzo

### CODE REVIEW

**Comment by minasmart** [comment]
Removing register won't work on node 12

**Comment by minasmart** [comment]
There's also separate babel rules for the build-lib, and src  directories. For build tooling, we don't really care what gets baked in or required. For src, we really do. And that config lives over [here](https://github.com/Shopify/js-buy-sdk/blob/master/build-lib/util/babel-config.js)

**Comment by mikkoh** [comment]
@minasmart what do you mean Node 12? Stable is ~4 and experimental newest is ~6?

**Comment by minasmart** [comment]
We have to support node `v0.12` up to current for building the library. We have to support ie9 for the actual SDK code.

**Comment by richgilbank** [comment]
@minasmart Support for v0.12 wasn't a hard-and-fast rule… it was based on estimated version usage at a time (~6 months ago) when building the SDK happened `postInstall` rather than `prePublish` as well, so to be able to use the SDK at all, one would have to build it themselves. Since that's no longer the case, I think it's worth reevaluating whether or not it's a requirement, particularly if it simplifies the codebase. 
It's also worth noting here that LTS support for `v0.12` [ends in < 4 months](https://github.com/nodejs/LTS) so it's definitely worth at least considering dropping it in the near future.

**Comment by minasmart** [comment]
@richgilbank great to know. I'd be more than happy to not have to run so many parallel builds in CI and update to a newer root version 😄

**Pull request closed without merging**
