### PR TITLE
Focus on checkout button when adding product to cart

### PR DESCRIPTION
**Pull request by harismahmood89**
- Auto focus on `#checkout` button in cart when triggering an "add to cart" event.

Please review @xto @richgilbank

### CODE REVIEW

**Comment by minasmart** [comment]
👍

**Comment by richgilbank** [comment]
Since the cart's essentially functioning as a modal window, focus should probably be returned to its previous state if the modal (/cart) is closed, i.e by pressing escape (much like the "Get Started" dialog on shopify.com)

**Comment by harismahmood89** [comment]
Good call, @richgilbank

**Comment by harismahmood89** [comment]
Adding this functionality to #82

**Pull request closed without merging**
